resolver: lts-11.13
packages:
- .

# https://github.com/NorfairKing/validity/tree/development
extra-deps:

  - git: https://github.com/NorfairKing/validity
    commit: 4de0a0eff895ee2dc7f0bc17cf65d3acb0a0cd5a
    subdirs:
      - validity
      - validity-aeson
      - validity-bytestring
      - validity-containers
      - validity-path
      - validity-scientific
      - validity-text
      - validity-time
      - validity-unordered-containers
      - validity-uuid
      - validity-vector
      - genvalidity
      - genvalidity-aeson
      - genvalidity-bytestring
      - genvalidity-containers
      - genvalidity-hspec
      - genvalidity-hspec-aeson
      - genvalidity-hspec-binary
      - genvalidity-hspec-cereal
      - genvalidity-hspec-hashable
      - genvalidity-path
      - genvalidity-property
      - genvalidity-scientific
      - genvalidity-text
      - genvalidity-time
      - genvalidity-unordered-containers
      - genvalidity-uuid
      - genvalidity-vector
